# Generated by Django 4.0 on 2021-12-22 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="challenge_id",
            new_name="challenge",
        ),
    ]
