# Generated by Django 4.0 on 2021-12-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_user_taskverification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskverification",
            name="verified_at",
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
